### PR TITLE
Bump parboiled which has fixes for JDK17

### PR DESCRIPTION
**Pull request by mdedetrich**
The issues with parboiled and unsafe access have been solved in latest release

### CODE REVIEW

**Comment by mdedetrich** [comment]
So this works with JDK17 but you then have to drop JDK8, @ennru what do you want to do here?

**Comment by ennru** [comment]
Not an obvious choice. People will need to use the `release` flag to produce jars for older versions, I guess.
We can release this as 1.0 and require JDK 11. Please update the readme about that.

**Comment by mdedetrich** [comment]
I did some thinking about this and I am more leaning towards removing JDK11/JDK17 from the pipeline and leaving it as is for now. If JDK8 is going to be dropped I think it makes sense to update sbt-paradox (i.e. updating parboiled to 1.4.1) to reflect this, possibly also as a new major release and then re-releasing the dependent libraries such as this one.

Do you agree?

**Comment by ennru** [comment]
Yes. Let's stick to the old Java world. Starting on the Paradox end with the upgrades makes more sense than in this leaf project.

**Comment by mdedetrich** [comment]
Cool, I will convert this to a draft PR and will rebase when a new release of sbt-paradox is made

**Comment by ennru** [comment]
Fixed with #241

**Pull request closed without merging**
